### ISSUE TITLE
Refactor: UI 및 CSS 개선

### ISSUE THREAD

**Issue by se030** [se030/pandaspread#10]
## 👨‍🔧 Tasks

- [x] 그래프 색상에 d3 interpolate 적용

- [x] Sidebar 스크롤 영역 높이에서 누락되는 노드 보정

- [x] Sidebar 정렬 버튼 마크업만 구현
