### ISSUE TITLE
Feat: UI/UX 관련 요소 구현

### ISSUE THREAD

**Issue by se030** [se030/pandaspread#20]
## 💎 Tasks

- [ ] title, favicon

- [x] 필요한 부분에 로딩 UI 추가

  - 결측치 삭제, 정렬 (애니메이션?)

- [x] 스크롤 빠르게 이동시 빈 영역 드러나는 이슈

  - 윈도우를 크게 잡기?

- [ ] Td 디테일 잡기
